apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data-claim
  labels:
    pvc: app-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 1Gi
